version: 2
jobs:
  build:
    working_directory: /src
    docker:
      - image: numtide/circleci-nix
    steps:
      - checkout
      - run:
          name: Build
          command: nix-build -A hies
